permalink: pretty
title: OSSCE
url: https://bluescreen.ing
description: Oxford Society for Science Communication and Engagement, a student-run society at the University of Oxford.
author: Lucy Back